project:
  type: website
  output-dir: docs

website:
  title: "Janelle L. Morano"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: mentorship.qmd
        text: Mentorship

format:
  html:
    highlight-style: a11y
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



