---
title: "Mentorship"
about: 
  template: marquee
---

I believe that mentoring and training students is integral to how I conduct my scientific research program. I am fortunate to work with motivated students who willingly challenge themselves to gain new skills and develop their critical thinking. My students have worked with me on a variety of projects, and have developed and pursued their own research questions to achieve peer-reviewed publications, honors theses, and career advancement.


### Nicola Love
Cornell University undergraduate, class of 2018
Senior honors thesis: Do blue jays respond to information about predators encoded in tufted titmice alarm calls?

### Matthew Lam
Cornell University undergraduate, class of 2018
Lab training and independent research: Blue jay alarm call classification and blue jay feeding behavior responses to predators.
Major in Biology and Economics

### Julia Dorn
Cornell University undergraduate, class of 2018
Lab training and independent research: Predator threat information encoding in black-capped chickadee alarm calls
Major in Biology and Society

### Stephanie Izard
Cornell University undergraduate, class of 2016
Lab training and independent research: Predator threat information encoding in black-capped chickadee alarm calls

### Elizabeth McDonald
Cornell University undergraduate, class of 2013
Senior Honors Thesis: Changes in acoustic behavior of sperm whales in the Gulf of Mexico following the Deepwater Horizon oil spill

Published McDonald, E., J. L. Morano, A.I. DeAngelis, A. N. Rice. 2017. Building time-budgets from bioacoustic signals to measure population-level changes in behavior: a case study with sperm whales in the Gulf of Mexico. Ecological Indicators 72: 360-364. DOI: 10.1016/j.ecolind.2016.08.028 
