---
title: "Publications"
about: 
  template: marquee
---

Green, A. R., Murphy, A., Collison, B. R., Sánchez-Nivicela, M., Anderson, H., **Morano, J. L.**, Williams, T. D., & Wilkinson, C. E. (2022). A response to Cafaro, Hansson & Götmark (2022): Shifting the narrative from overpopulation to overconsumption. Biological Conservation, 273, 109698. https://doi.org/10.1016/j.biocon.2022.109698

Friedland, K., E. Methratta, A. Gill, S. Gaichas, T. Curtis, E. Adams, **J.L. Morano**, D. Crear, M. McManus, D. Brady. 2021. Resource occurrence and productivity in existing and proposed wind energy lease areas on the US Northeast Shelf. Frontiers in Marine Science 8 (2021): 336. https://doi-org.proxy.library.cornell.edu/10.3389/fmars.2021.629230

Odom, K.J., M. Araya-Salas, **J.L. Morano**, R. Ligon, G. Leighton, C. Taff, A. Dalziell, A. Billings, R. Germain, Ryan, M. Pardo, L. Guimarães de Andrade, D. Hedwig, S. Keen, Y. Shiu, R. Charif, M. Webster, A.N. Rice. 2021. Comparative bioacoustics: a roadmap for quantifying and comparing animal sounds across diverse taxa. Biological Reviews. https://doi-org.proxy.library.cornell.edu/10.1111/brv.12695

**Morano, J. L.**, Tielens, J. T., Muirhead, C. A., Estabrook, B. J., Sullivan, P. J., Dugan, P. J., Clark, C. W., & Rice, A. N. 2020. Seasonal movements of Gulf of Mexico sperm whales following the Deepwater Horizon oil spill and the limitations of impact assessments. Marine Pollution Bulletin, 161, 111627. https://doi.org/10.1016/j.marpolbul.2020.111627

Friedland, K. D., R. E. Morse, N. Shackell, J. C. Tam, **J.L. Morano**, J. R. Moisan, D. C. Brady. 2020. Changing physical conditions and lower and upper trophic level responses on the US Northeast Shelf. Frontiers in Marine Science, 7. https://doi.org/10.3389/fmars.2020.567445

Ligon, R.A., C.D. Diaz, **J.L. Morano**, J. Troscianko, M. Stevens, A. Mosekeland, E. Scholes III. 2018. Evolution of correlated complexity in the radically different courtship signals of birds-of-paradise. PLOS Biology 16(11): e2006962. https://doi.org/10.1371/journal.pbio.2006962
 
McDonald, E., **J. L. Morano**, A.I. DeAngelis, A. N. Rice. 2017. Building time-budgets from bioacoustic signals to measure population-level changes in behavior: a case study with sperm whales in the Gulf of Mexico. Ecological Indicators 72: 360-364. DOI: 10.1016/j.ecolind.2016.08.028.
 
Rice, A. N., **J. L. Morano**, Hodge, K. B., C. A. Muirhead. 2016. Spatial and temporal patterns of toadfish and black drum chorusing activity in the South Atlantic Bight. Environmental Biology of Fishes 99: 705-716. DOI: 10.1007/s10641-016-0511-z.

Hodge, K. B., C. A. Muirhead, **J. L. Morano**, A. N. Rice. 2015. North Atlantic right whale occurrence in two wind planning areas along the mid-Atlantic U.S. coast: implications for management. Endangered Species Research 28(3):225-234. DOI: 10.3354/esr00683.
 
Rice, A. N., **J. L. Morano**. 2015. Changes in ocean temperature impact fish acoustic communication: implications for reproductive timing and acoustic community structure. Integrative and Comparative Biology 55(Supplement 1): e151.
 
**Morano, J. L.**, D. P. Salisbury, A. N. Rice, K. L. Conklin, K. L. Falk, C. W. Clark. 2012. Seasonal and geographical patterns of fin whale song in the western North Atlantic Ocean. Journal of the Acoustical Society of America, 132(2): 1207-1012. DOI: 10.1121/1.4730890.
 
**Morano, J. L.**, A. N. Rice, J. T. Tielens, B. J. Estabrook, A. Murray, B. L. Roberts, C. W. Clark.  2012. Acoustically detected year-round presence of right whales in an urbanized migration corridor. Conservation Biology, 26(4): 698-707. DOI: 10.1111/j.1523-1739.2012.01866.x
 
Dugan, P. J., D. W. Ponirakis, J. A. Zollweg, M. S. Pitzrick, **J. L. Morano**, A. M. Warde, A. N. Rice, C. W. Clark, S. M. Van Parijs. 2011. SEDNA – Bioacoustic analysis toolbox. IEEE OCEANS 2011, 1-10.
 
Clark, C. W., C. Tremblay, M. Fowler, C. Diamond, D. Ponirakis, C. McCarthy, **J. L. Morano**, C. Muirhead, A. Murray, L. Rowland, K. Vannicola, and A. Warde.  2008. Monitoring, measuring and describing ocean noise over ecologically viable scales with applications to impacts on large whales.  Journal of the Acoustical Society of America, 123(5): 2987. DOI: 10.1121/1.2932520.

# Published Abstracts
Cheyne, H. A., P. M. Marchetto, R. C. Mack, D. P. Salisbury, and **J. L. Morano**. 2014. Improving acoustic time-of-arrival location estimates by correcting for temperature drift in time base oscillators. Journal of the Acoustical Society of America, 135: 2367. DOI: 10.1121/1.4877802

# Data Products
Seasonal Movements of Gulf of Mexico Sperm Whales Following the Deepwater Horizon Oil Spill and the Limitations of Impact Assessments, Data Products (Jun 2010 to Feb 2012). (2020). NOAA National Centers for Environmental Information. https://doi.org/10.25921/qrvr-5386